# Generated by Django 4.1.5 on 2024-05-06 17:49

import cloths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0002_alter_userimage_image_alter_userimage_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclothes',
            name='image',
            field=models.ImageField(upload_to=cloths.models.clothes_image_upload_to),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to=cloths.models.user_image_upload_to),
        ),
    ]
